### ISSUE TITLE
Bulky Assets on the pages making the pages load slower

### ISSUE THREAD

**Issue by adityak1911** [PhysicsClubSVNIT/PhysicsClubSVNIT.github.io#1]
Bulky Assets on the pages making the pages load slower,
On homepage the background image is way too large

**Comment by adithyarao3103** [comment]
[Resolved](https://github.com/PhysicsClubSVNIT/PhysicsClubSVNIT.github.io/commit/6e17f72eae59bc089f58196e6e986a7899e2517d)
